// Catálogo de emojis do seletor de reações.
// Cada entrada é [emoji, palavras-chave de busca em pt-BR].

export type EmojiEntry = readonly [emoji: string, keywords: string]

export type EmojiCategory = {
  id: string
  label: string
  icon: string
  emojis: readonly EmojiEntry[]
}

export const EMOJI_CATEGORIES: readonly EmojiCategory[] = [
  {
    id: 'smileys',
    label: 'Carinhas',
    icon: '😀',
    emojis: [
      ['😀', 'sorriso feliz alegre'],
      ['😃', 'sorriso feliz alegre'],
      ['😄', 'sorriso feliz alegre'],
      ['😁', 'sorriso radiante feliz'],
      ['😆', 'risada rindo'],
      ['😅', 'risada alivio suor'],
      ['🤣', 'rolando de rir gargalhada'],
      ['😂', 'chorando de rir gargalhada'],
      ['🙂', 'sorriso leve'],
      ['🙃', 'de cabeca para baixo ironia'],
      ['😉', 'piscada'],
      ['😊', 'feliz timido'],
      ['😇', 'anjo inocente'],
      ['🥰', 'apaixonado amor coracoes'],
      ['😍', 'apaixonado olhos de coracao'],
      ['🤩', 'estrelas uau incrivel'],
      ['😘', 'beijo'],
      ['😋', 'delicia gostoso lingua'],
      ['😛', 'lingua brincadeira'],
      ['🤪', 'louco doido'],
      ['🤨', 'sobrancelha duvida ceticismo'],
      ['🧐', 'monoculo analisando investigando'],
      ['🤓', 'nerd estudioso'],
      ['😎', 'oculos de sol estiloso legal'],
      ['🥳', 'festa comemoracao'],
      ['😏', 'sorriso maroto ironia'],
      ['😒', 'sem graca desanimado'],
      ['😞', 'triste decepcionado'],
      ['😔', 'triste pensativo'],
      ['😟', 'preocupado'],
      ['🙁', 'triste'],
      ['😣', 'perseverando esforco'],
      ['😖', 'confuso frustrado'],
      ['😫', 'cansado exausto'],
      ['😩', 'cansado desanimado'],
      ['🥺', 'suplicante pidao'],
      ['😢', 'chorando triste'],
      ['😭', 'chorando muito triste'],
      ['😤', 'bufando irritado determinado'],
      ['😠', 'bravo irritado'],
      ['😡', 'furioso raiva'],
      ['🤬', 'xingando palavrao'],
      ['🤯', 'mente explodindo chocado'],
      ['😳', 'envergonhado surpreso'],
      ['🥵', 'calor quente'],
      ['🥶', 'frio congelando'],
      ['😱', 'gritando de medo choque'],
      ['😨', 'assustado medo'],
      ['😰', 'ansioso suor'],
      ['😥', 'aliviado triste'],
      ['😓', 'suor cansado'],
      ['🤗', 'abraco'],
      ['🤔', 'pensando duvida hmm'],
      ['🤭', 'ops risadinha'],
      ['🤫', 'silencio shh segredo'],
      ['🤥', 'mentira pinoquio'],
      ['😶', 'sem boca sem palavras'],
      ['😐', 'neutro'],
      ['😑', 'inexpressivo'],
      ['😬', 'careta constrangido'],
      ['🙄', 'revirando os olhos'],
      ['😴', 'dormindo sono'],
      ['🤤', 'babando'],
      ['😪', 'sono cansado'],
      ['😮', 'surpreso boca aberta uau'],
      ['😯', 'surpreso'],
      ['😲', 'chocado espantado'],
      ['🥱', 'bocejo entediado'],
      ['🤒', 'doente febre'],
      ['🤕', 'machucado ferido'],
      ['🤢', 'enjoado nojo'],
      ['🤮', 'vomitando nojo'],
      ['🤧', 'espirro resfriado'],
      ['😷', 'mascara doente'],
      ['🥴', 'tonto zonzo'],
      ['🤠', 'caubói'],
      ['🤡', 'palhaco'],
      ['💩', 'coco merda ruim'],
      ['👻', 'fantasma assombrado'],
      ['💀', 'caveira morto'],
      ['👽', 'alien et'],
      ['🤖', 'robo bot automacao ia'],
      ['🎃', 'abobora halloween'],
    ],
  },
  {
    id: 'gestures',
    label: 'Gestos',
    icon: '👍',
    emojis: [
      ['👍', 'joinha positivo curti aprovo like'],
      ['👎', 'negativo nao curti dislike'],
      ['👏', 'palmas aplausos parabens'],
      ['🙌', 'maos ao alto comemoracao'],
      ['🤝', 'aperto de mao acordo combinado'],
      ['🙏', 'obrigado por favor prece'],
      ['💪', 'forca musculo'],
      ['✌️', 'paz vitoria'],
      ['🤞', 'dedos cruzados torcendo'],
      ['🤟', 'te amo rock'],
      ['🤘', 'rock chifres'],
      ['👌', 'ok certo perfeito'],
      ['🤌', 'italiano dedos'],
      ['🤙', 'me liga shaka'],
      ['👈', 'aponta esquerda'],
      ['👉', 'aponta direita'],
      ['👆', 'aponta cima isso'],
      ['👇', 'aponta baixo'],
      ['☝️', 'dedo indicador atencao'],
      ['✋', 'mao parada stop'],
      ['🖐️', 'mao aberta'],
      ['🖖', 'vulcano spock'],
      ['👋', 'tchau ola aceno'],
      ['🤚', 'mao levantada'],
      ['🖕', 'dedo do meio'],
      ['✍️', 'escrevendo anotando'],
      ['🤳', 'selfie'],
      ['💅', 'unha esmalte nem ligo'],
      ['🦾', 'braco mecanico forca'],
      ['👀', 'olhos olhando atencao'],
      ['👁️', 'olho'],
      ['🧠', 'cerebro ideia inteligencia'],
      ['🫀', 'coracao orgao'],
      ['👂', 'ouvido escutando'],
      ['👃', 'nariz'],
      ['🦻', 'audicao'],
      ['🗣️', 'falando voz'],
      ['👤', 'pessoa silhueta'],
      ['👥', 'pessoas time grupo'],
      ['🫂', 'abraco pessoas apoio'],
    ],
  },
  {
    id: 'people',
    label: 'Pessoas',
    icon: '🧑',
    emojis: [
      ['👶', 'bebe'],
      ['🧒', 'crianca'],
      ['🧑', 'pessoa'],
      ['👨', 'homem'],
      ['👩', 'mulher'],
      ['🧓', 'idoso'],
      ['🧑‍💻', 'dev programador desenvolvedor time'],
      ['👨‍💻', 'dev programador desenvolvedor'],
      ['👩‍💻', 'dev programadora desenvolvedora'],
      ['🧑‍🎨', 'design designer'],
      ['🧑‍🏫', 'professor ensinando'],
      ['🧑‍🔧', 'mecanico manutencao'],
      ['🧑‍🚀', 'astronauta lancamento'],
      ['🧑‍🚒', 'bombeiro incendio'],
      ['🕵️', 'detetive investigando'],
      ['💂', 'guarda'],
      ['🦸', 'heroi salvou'],
      ['🦹', 'vilao'],
      ['🧙', 'mago magica'],
      ['🧟', 'zumbi cansado'],
      ['🤦', 'facepalm mao na cara'],
      ['🤷', 'ombros sei la tanto faz'],
      ['🙋', 'levantando a mao duvida'],
      ['🙆', 'ok certo'],
      ['🙅', 'nao proibido'],
      ['💁', 'informacao atendimento'],
      ['🧘', 'meditacao calma zen'],
      ['🏃', 'correndo pressa sprint'],
      ['🚶', 'andando'],
      ['🕺', 'dancando comemoracao'],
      ['💃', 'dancando comemoracao'],
      ['🧑‍🤝‍🧑', 'juntos parceria time'],
    ],
  },
  {
    id: 'nature',
    label: 'Natureza',
    icon: '🌱',
    emojis: [
      ['🔥', 'fogo top incrivel bombando'],
      ['✨', 'brilho magia novo'],
      ['⭐', 'estrela destaque favorito'],
      ['🌟', 'estrela brilhante destaque'],
      ['💫', 'tontura estrela'],
      ['⚡', 'raio rapido energia'],
      ['💥', 'explosao impacto'],
      ['☀️', 'sol dia'],
      ['🌤️', 'sol nuvem'],
      ['☁️', 'nuvem cloud'],
      ['🌧️', 'chuva'],
      ['⛈️', 'tempestade caos'],
      ['🌈', 'arco iris'],
      ['❄️', 'neve frio congelado'],
      ['🌊', 'onda mar'],
      ['🌪️', 'tornado caos furacao'],
      ['🌱', 'broto crescimento comeco'],
      ['🌿', 'planta folha'],
      ['🍀', 'trevo sorte'],
      ['🌳', 'arvore'],
      ['🌵', 'cacto seco'],
      ['🌹', 'rosa flor'],
      ['🌻', 'girassol'],
      ['🌸', 'flor cerejeira'],
      ['🍂', 'folhas outono'],
      ['🐛', 'bug inseto erro'],
      ['🐞', 'joaninha bug'],
      ['🦋', 'borboleta transformacao'],
      ['🐢', 'tartaruga lento devagar'],
      ['🐌', 'caracol lento'],
      ['🐝', 'abelha ocupado'],
      ['🐍', 'cobra python'],
      ['🐙', 'polvo'],
      ['🐳', 'baleia'],
      ['🦄', 'unicornio raro magico'],
      ['🐴', 'cavalo'],
      ['🐶', 'cachorro'],
      ['🐱', 'gato'],
      ['🦉', 'coruja sabedoria noite'],
      ['🐧', 'pinguim'],
    ],
  },
  {
    id: 'food',
    label: 'Comida',
    icon: '🍕',
    emojis: [
      ['☕', 'cafe coffee pausa'],
      ['🍵', 'cha'],
      ['🍺', 'cerveja comemoracao happy hour'],
      ['🍻', 'brinde comemoracao'],
      ['🥂', 'brinde comemoracao'],
      ['🍾', 'champanhe comemoracao'],
      ['🍕', 'pizza'],
      ['🍔', 'hamburguer'],
      ['🍟', 'batata frita'],
      ['🌮', 'taco'],
      ['🍿', 'pipoca show novela'],
      ['🍫', 'chocolate'],
      ['🍪', 'biscoito cookie'],
      ['🎂', 'bolo aniversario'],
      ['🍰', 'bolo fatia'],
      ['🍩', 'donut rosquinha'],
      ['🍦', 'sorvete'],
      ['🍎', 'maca fruta'],
      ['🍌', 'banana'],
      ['🍉', 'melancia'],
      ['🥑', 'abacate'],
      ['🥦', 'brocolis saudavel'],
      ['🌶️', 'pimenta picante'],
      ['🧂', 'sal'],
      ['🍞', 'pao'],
      ['🥗', 'salada saudavel'],
      ['🍜', 'lamen macarrao'],
      ['🍣', 'sushi'],
      ['🥤', 'refrigerante bebida'],
      ['🧃', 'suco caixinha'],
    ],
  },
  {
    id: 'activity',
    label: 'Atividades',
    icon: '🎉',
    emojis: [
      ['🎉', 'festa comemoracao parabens'],
      ['🎊', 'confete festa'],
      ['🎈', 'balao festa'],
      ['🎁', 'presente'],
      ['🏆', 'trofeu vitoria conquista'],
      ['🥇', 'primeiro lugar ouro'],
      ['🥈', 'segundo lugar prata'],
      ['🥉', 'terceiro lugar bronze'],
      ['🏅', 'medalha'],
      ['⚽', 'futebol bola'],
      ['🏀', 'basquete'],
      ['🏐', 'volei'],
      ['🎾', 'tenis'],
      ['🎯', 'alvo foco objetivo meta'],
      ['🎲', 'dado sorte aleatorio'],
      ['🎮', 'videogame jogo'],
      ['🕹️', 'joystick controle'],
      ['🧩', 'quebra cabeca peca encaixe'],
      ['🎨', 'arte design'],
      ['🎭', 'teatro drama'],
      ['🎬', 'cinema acao'],
      ['🎤', 'microfone apresentacao'],
      ['🎧', 'fone musica foco'],
      ['🎵', 'musica nota'],
      ['🥁', 'bateria tambor'],
      ['🎸', 'guitarra'],
      ['🚀', 'foguete deploy lancamento rapido'],
      ['🛠️', 'ferramentas manutencao'],
      ['⚙️', 'engrenagem config processo'],
      ['🧰', 'caixa de ferramentas'],
    ],
  },
  {
    id: 'objects',
    label: 'Objetos',
    icon: '💡',
    emojis: [
      ['💡', 'ideia lampada insight'],
      ['💻', 'notebook computador dev'],
      ['🖥️', 'monitor computador'],
      ['⌨️', 'teclado'],
      ['🖱️', 'mouse'],
      ['📱', 'celular mobile'],
      ['🔌', 'tomada plugado integracao'],
      ['🔋', 'bateria energia'],
      ['💾', 'disquete salvar'],
      ['💿', 'cd disco'],
      ['📦', 'caixa pacote entrega deploy'],
      ['📈', 'grafico subindo crescimento melhora'],
      ['📉', 'grafico caindo queda piora'],
      ['📊', 'grafico barras metricas dados'],
      ['📅', 'calendario data prazo'],
      ['⏰', 'despertador alarme prazo'],
      ['⏳', 'ampulheta tempo espera'],
      ['⌛', 'tempo esgotado'],
      ['⏱️', 'cronometro timer'],
      ['📌', 'alfinete fixar importante'],
      ['📎', 'clipe anexo'],
      ['📝', 'anotacao nota documentacao'],
      ['📄', 'documento arquivo'],
      ['📋', 'prancheta checklist backlog'],
      ['📚', 'livros estudo documentacao'],
      ['🔍', 'lupa busca investigacao'],
      ['🔎', 'lupa busca'],
      ['🔒', 'cadeado seguranca bloqueado'],
      ['🔓', 'cadeado aberto liberado'],
      ['🔑', 'chave acesso solucao'],
      ['🔨', 'martelo consertar'],
      ['🪛', 'chave de fenda ajuste'],
      ['🧯', 'extintor incendio emergencia'],
      ['🩹', 'curativo remendo gambiarra workaround'],
      ['🧹', 'vassoura limpeza refatoracao'],
      ['🗑️', 'lixeira descartar remover'],
      ['💰', 'dinheiro custo orcamento'],
      ['💸', 'dinheiro voando gasto custo'],
      ['🔔', 'sino notificacao alerta'],
      ['🔕', 'sino mudo silencio'],
      ['📢', 'megafone anuncio comunicado'],
      ['📣', 'megafone divulgacao'],
      ['🧪', 'teste experimento laboratorio'],
      ['🔬', 'microscopio analise detalhe'],
      ['🧭', 'bussola direcao norte'],
      ['🗺️', 'mapa roadmap plano'],
      ['🚦', 'semaforo status'],
      ['🚧', 'obras em andamento wip'],
      ['🩺', 'estetoscopio diagnostico saude'],
      ['🛡️', 'escudo protecao seguranca'],
    ],
  },
  {
    id: 'symbols',
    label: 'Símbolos',
    icon: '❤️',
    emojis: [
      ['❤️', 'coracao amor amei'],
      ['🧡', 'coracao laranja'],
      ['💛', 'coracao amarelo'],
      ['💚', 'coracao verde'],
      ['💙', 'coracao azul'],
      ['💜', 'coracao roxo'],
      ['🖤', 'coracao preto'],
      ['🤍', 'coracao branco'],
      ['💔', 'coracao partido triste'],
      ['💯', 'cem perfeito concordo total'],
      ['✅', 'check feito concluido ok'],
      ['☑️', 'marcado check'],
      ['✔️', 'certo correto'],
      ['❌', 'errado nao remover'],
      ['⛔', 'proibido bloqueado'],
      ['🚫', 'proibido nao'],
      ['⚠️', 'atencao aviso risco'],
      ['❗', 'exclamacao importante urgente'],
      ['❕', 'exclamacao'],
      ['❓', 'duvida pergunta'],
      ['❔', 'duvida'],
      ['➕', 'mais adicionar'],
      ['➖', 'menos remover'],
      ['🔁', 'repetir loop recorrente'],
      ['🔄', 'atualizar sincronizar refazer'],
      ['⏩', 'avancar rapido'],
      ['⏪', 'voltar'],
      ['🔼', 'subir prioridade'],
      ['🔽', 'descer prioridade'],
      ['🆗', 'ok'],
      ['🆕', 'novo'],
      ['🔝', 'topo melhor'],
      ['💤', 'sono parado inativo'],
      ['♻️', 'reciclar reaproveitar reuso'],
      ['🏳️', 'bandeira branca desisto'],
      ['🚩', 'bandeira alerta marcado'],
      ['🎯', 'alvo meta foco'],
    ],
  },
] as const

/** Emojis sugeridos quando o participante ainda não usou nenhum. */
export const DEFAULT_RECENT_EMOJIS = ['👍', '🔥', '😂', '🎉', '❤️', '👀', '🤔', '😢'] as const

export const RECENT_EMOJIS_STORAGE_KEY = 'retro_recent_emojis'
export const MAX_RECENT_EMOJIS = 16

/**
 * Valida se um valor é um emoji aceitável como reação: precisa começar com um
 * pictograma e não pode conter letras, números ou espaços (evita usar o campo
 * de reações como texto livre).
 */
export function isEmoji(value: unknown): value is string {
  if (typeof value !== 'string') return false
  if (value.length === 0 || value.length > 16) return false
  if (/[\p{L}\p{N}\s]/u.test(value)) return false
  return /^\p{Extended_Pictographic}/u.test(value)
}

export function searchEmojis(query: string): EmojiEntry[] {
  const term = query
    .trim()
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')

  if (!term) return []

  const results: EmojiEntry[] = []
  const seen = new Set<string>()

  for (const category of EMOJI_CATEGORIES) {
    for (const entry of category.emojis) {
      if (seen.has(entry[0])) continue
      if (entry[1].includes(term) || entry[0] === query.trim()) {
        results.push(entry)
        seen.add(entry[0])
      }
    }
  }

  return results
}
